### ISSUE TITLE
Artifacts in repository

### ISSUE THREAD

**Issue by Paebbels** [BR1py/itertree#21]
There are artifact files in the repository in `./dist`.

**Comment by BR1py** [comment]
Do you mean the file:
 [itertree-1.0.1.tar.gz](https://github.com/BR1py/itertree/blob/dev/dist/itertree-1.0.1.tar.gz)
should not be commited?

**Comment by Paebbels** [comment]
Yes. You have all release data at PyPI.

If needed, you can upload CI pipeline results as artifacts/assets to tagged releases in GitHub.

Artifacts in the Git repository increases the repository size, slows down CI (download/clone time) and is not an intend of Git. Only sources and config is saved in the repository.

**Comment by BR1py** [comment]
I will delete the artifacts with next commit
