### ISSUE TITLE
Invalid escape sequence in doc-strings.

### ISSUE THREAD

**Issue by Paebbels** [BR1py/itertree#22]
Proposed fixes:
* Some doc-strings contain wrong text snippets: `True\False` &rarr; `True/False`  
  See #19 
* Fixed reference to `pyTooling`  
  See #20

This causes errors when using `itertree`:
```raw
  C:\Program Files\Python3.11\Lib\ast.py:50: in parse
    return compile(source, filename, mode, flags,
E     File "C:\Program Files\Python3.11\Lib\site-packages\itertree\itree_mathsets.py", line 580
E       """
E       ^^^
E   SyntaxError: invalid escape sequence '\F'
```

**Comment by BR1py** [comment]
I have approved the Pull requests, hope all illegal escapes are out now.
