### ISSUE TITLE
Link to documentation

### ISSUE THREAD

**Issue by Paebbels** [BR1py/itertree#28]
Please add a link or shield to the documentation at https://itertree.readthedocs.io/

![image](https://github.com/BR1py/itertree/assets/956109/3306f2b4-cb13-40ff-b477-c5c3c167104e)

Please also use the URL feature on the right side to add a URL e.g. to the documentation.

![image](https://github.com/BR1py/itertree/assets/956109/dae91e43-bc2d-435d-adb8-36be4cd67c59)

**Comment by BR1py** [comment]
Added the requested changes on dev will be intergated in next relese version
