### ISSUE TITLE
Inheritance from iTree is tricky

### ISSUE THREAD

**Issue by lverweijen** [BR1py/itertree#30]
I'm not sure whether I'm supposed to inherit from `iTree`, but doing so seems tricky.
Perhaps this should be made easier, better documented or recommended against.

Here some things to keep into account when inheriting:
- `repr(tree)` is hardcoded to write "iTree" instead of classname and needs to be overridden.
- Methods `append`, `extend`, `appendleft`, `extendleft`, `setitem` all call the iTree constructor (implicit construction) and would probably need to be overriden.
- Even if the type-specific constructor were called, all above methods require that the constructor supports the signature `subclass.__init__(value=value)`. It's not uncommon for subclasses to change the signature of `__init__`.
- `iTreeRenderer` always print "iTree" and needs to be subclassed too (or it should probably use `type(tree).__name__` instead)
- The `render` method on iTree implicitly creates an iTreeRenderer and needs to be overridden too

At the same time, inheriting from built-in classes such as dict and list is also not so straightforward.
Maybe not inheriting from iTree and building some kind of MyTree-api around it, is generally the better solution.

**Comment by BR1py** [comment]
I know I made the proposal to you and I was aware of this. But yes we will improve this for next release. At least the the internal functions of the main iTree() class should work. The adation of the renderer is easy. But im not sure about the serializer here you might need a special one and this is very tricky code.

But I can predict here improvements soon.

**Comment by BR1py** [comment]
I rechecked the code an it looks really easy. I think we can adapt whole code for "perfect" inheritance.

**Comment by BR1py** [comment]
I close the issue inheritance of iTree class is improved in new release 1.1.2
