### ISSUE TITLE
Importing 'itertree' gives a ModuleNotFoundError

### ISSUE THREAD

**Issue by Paebbels** [BR1py/itertree#35]
> ModuleNotFoundError: No module named 'itertree.itree_indepth_helpers'

It's used like that:
```py
from itertree import iTree
```
Source: https://github.com/pyTooling/pyTooling/blob/main/tests/performance/Tree/IterTree.py#L32

**Comment by BR1py** [comment]
I can reproduce the issue, try to solve it soon.

**Comment by BR1py** [comment]
A subfolder of the code was not packed in the package. The package must be repacked. New release will come soon.

**Comment by Paebbels** [comment]
Thanks. I saw it a while ago but was unsure if it's a package error or on my side.

@yurivict

**Comment by BR1py** [comment]
Issue should be solved in release 1.1.3

**Comment by Paebbels** [comment]
Thanks. I'll test it soon.

----
Btw. did you experiment with Cython?
