### ISSUE TITLE
name 'iTreeTagIdx' is not defined

### ISSUE THREAD

**Issue by sieumap43** [BR1py/itertree#4]
As the title suggests, iTreeTagIdx doesn't exist. Even when I did from itertree import *.
Python 3.8
itertree 0.7.3
![image](https://user-images.githubusercontent.com/26580120/168051900-0e0abca8-d727-4303-bb76-4f6cde98276c.png)

**Comment by BR1py** [comment]
The name was shortened from `iTreeTagIdx` to `TagIdx` only. 
Where did you find the hint to the class `iTreeTagIdx` ? Maybe documentation must be updated?

**Comment by sieumap43** [comment]
Thank you for the reply. The README.md in the front of your repo still has iTreeTagIdx.
![image](https://user-images.githubusercontent.com/26580120/168787813-71826c9b-4efd-43a4-bd50-9e935b34f2c5.png)

**Comment by BR1py** [comment]
Changed the readme.md thanks for the hint.
